### ISSUE TITLE
ValueError: attempt to get argmax of an empty sequence

### ISSUE THREAD

**Issue by cneud** [qurator-spk/sbb_textline_detection#43]
For this page https://digital.staatsbibliothek-berlin.de/werkansicht?PPN=PPN1701685183&PHYSID=PHYS_0020&DMDID=, I get:

```
09:25:45.937 INFO processor.OcrdSbbTextlineDetectorRecognize - INPUT FILE 19 / <OcrdFile fileGrp=OCR-D-IMG-BIN, ID=FILE_0020_OCR-D-IMG-BIN, mimetype=application/vnd.prima.page+xml, url=OCR-D-IMG-BIN/FILE_0020_OCR-D-IMG-BIN.xml, local_filename=OCR-D-IMG-BIN/FILE_0020_OCR-D-IMG-BIN.xml]/>
Traceback (most recent call last):
  File "/usr/local/bin/ocrd-sbb-textline-detector", line 8, in <module>
    sys.exit(ocrd_sbb_textline_detector())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/qurator/sbb_textline_detector/ocrd_cli.py", line 31, in ocrd_sbb_textline_detector
    return ocrd_cli_wrap_processor(OcrdSbbTextlineDetectorRecognize, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ocrd/decorators/__init__.py", line 81, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ocrd/processor/helpers.py", line 68, in run_processor
    processor.process()
  File "/usr/local/lib/python3.6/dist-packages/qurator/sbb_textline_detector/ocrd_cli.py", line 73, in process
    x.run()
  File "/usr/local/lib/python3.6/dist-packages/qurator/sbb_textline_detector/main.py", line 2061, in run
    image_page,page_coord=self.extract_page()
  File "/usr/local/lib/python3.6/dist-packages/qurator/sbb_textline_detector/main.py", line 402, in extract_page
    cnt = contours[np.argmax(cnt_size)]
  File "<__array_function__ internals>", line 6, in argmax
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 1186, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
```

**Comment by cneud** [comment]
Confirmed fixed in current version.
