### ISSUE TITLE
Broken CI

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/sbb_textline_detection#64]
https://github.com/mikegerber/sbb_textline_detection/runs/8335240446 is broken.

- [x] Why Python 3.7? I think it does not even work with this Python version
- [x] Does the CI do something useful? I was not even aware that there were any tests implemented for sbb_textline_detection
- [x] Fix the build

**Comment by mikegerber** [comment]
Python 3.7 should work, TF 1.15 is available there. I also cannot reproduce the error in https://github.com/mikegerber/sbb_textline_detection/runs/8335240446 - It happens while doing `pip install .` and in `setuptools`:

```
$ pip install .

Processing /home/travis/build/mikegerber/sbb_textline_detection

  Preparing metadata (setup.py) ... error

  error: subprocess-exited-with-error

  

  × python setup.py egg_info did not run successfully.

  │ exit code: 1

  ╰─> [22 lines of output]

      Traceback (most recent call last):

        File "<string>", line 36, in <module>

        File "<pip-setuptools-caller>", line 14, in <module>

        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>

          from setuptools.dist import Distribution

        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>

          from ._importlib import metadata

        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_importlib.py", line 28, in <module>

          disable_importlib_metadata_finder(metadata)

        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_importlib.py", line 12, in disable_importlib_metadata_finder

          import importlib_metadata

        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 471, in <module>

          __version__ = version(__name__)

        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 438, in version

          return distribution(package).version

        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 411, in distribution

          return Distribution.from_name(package)

        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 179, in from_name

          dists = resolver(name)

        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 886, in find_distributions

          found = self._search_paths(context.name, context.path)

      AttributeError: 'str' object has no attribute 'name'

      [end of output]
```

Maybe Travis is using a different setuptools version?

**Comment by mikegerber** [comment]
The "test" is just installing and calling `ocrd-sbb-textline-detector --help`, so it's a start.

**Comment by mikegerber** [comment]
However, under Python 3.7 it's broken anyway:

```
130 ↵ [tmp.1238665]mike@leguin sbb_textline_detection % sbb_textline_detector                                      fix/not-detecting-any-regions-and-lines ?
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/mike/.virtualenvs/tmp.1238665/bin/sbb_textline_detector", line 5, in <module>
    from qurator.sbb_textline_detector import main
  File "/home/mike/devel/sbb_textline_detection/qurator/sbb_textline_detector/__init__.py", line 1, in <module>
    from .main import *
  File "/home/mike/devel/sbb_textline_detection/qurator/sbb_textline_detector/main.py", line 15, in <module>
    from keras.models import model_from_json
  File "/home/mike/.virtualenvs/tmp.1238665/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/mike/.virtualenvs/tmp.1238665/lib/python3.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/mike/.virtualenvs/tmp.1238665/lib/python3.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/mike/.virtualenvs/tmp.1238665/lib/python3.7/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/home/mike/.virtualenvs/tmp.1238665/lib/python3.7/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/home/mike/.virtualenvs/tmp.1238665/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/home/mike/.virtualenvs/tmp.1238665/lib64/python3.7/site-packages/tensorflow/__init__.py", line 102, in <module>
    from tensorflow_core import *
  File "/home/mike/.virtualenvs/tmp.1238665/lib64/python3.7/site-packages/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "/home/mike/.virtualenvs/tmp.1238665/lib64/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/home/mike/.virtualenvs/tmp.1238665/lib64/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/mike/.virtualenvs/tmp.1238665/lib64/python3.7/site-packages/tensorflow_core/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/mike/.virtualenvs/tmp.1238665/lib64/python3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/home/mike/.virtualenvs/tmp.1238665/lib64/python3.7/site-packages/tensorflow_core/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/mike/.virtualenvs/tmp.1238665/lib64/python3.7/site-packages/tensorflow_core/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/mike/.virtualenvs/tmp.1238665/lib64/python3.7/site-packages/tensorflow_core/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/mike/.virtualenvs/tmp.1238665/lib64/python3.7/site-packages/tensorflow_core/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/mike/.virtualenvs/tmp.1238665/lib64/python3.7/site-packages/tensorflow_core/core/framework/tensor_shape_pb2.py", line 42, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "/home/mike/.virtualenvs/tmp.1238665/lib64/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```
As this project is legacy, not suppossed to work on Python 3.7 IMHO, I'm disabling testing on Python 3.7 if there's noone objecting.
